dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  # All dot files in the root
  - \.*
  # This file
  - cspell.config.yaml
  # The docs requirements file
  - docs/requirements.in
  # Ignore licenses
  - licenses/*
  # The mypy configuration file
  - mypy.ini
  # The shared file for tool configuration
  - pyproject.toml
  # The setup file
  - setup.cfg
  # All grammar (text-mate) tokenization files
  - src/distronode_navigator/data/grammar/*.json
  # Theme files
  - src/distronode_navigator/data/themes/*.json
  # Anything in the vendored tokenization directory
  - src/distronode_navigator/tm_tokenize/*
  # requirements.txt is generated
  - requirements.txt
  # All fixture files in the tests directory
  - tests/fixtures/integration/actions/**/*.json
  # The tox configuration file
  - tox.ini

ignoreRegExpList:
  - "--\\w+" # distronode-navigator long CLI parameters
  - "(window|_screen|win)\\.\\w+" # curses calls e.g. getyx
  - "\\^.*$" # kegex regular expressions
  - "DISTRONODE_\\w+" # distronode environment variables
  - "curses\\.\\w+" # curses functions e.g. curses.doupdate
  - "monkeypatch\\.\\w+" # monkeypatch functions e.g. monkeypatch.setenv
  - "request\\.node\\.\\w+" # pytest request  e.g. request.node.nodeid
