---
# See https://github.com/distronode-community/devtools/blob/main/.github/workflows/push.yml
name: push
on:
  push:
    branches:
      - main
      - "releases/**"
      - "stable/**"

jobs:
  ack:
    uses: distronode/devtools/.github/workflows/push.yml@main
